version: '3'
services:
  app:
    build: ./
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: always
    environment:
      APP_PORT: $APP_PORT
      EXCHANGE_RATE_API_URL: $EXCHANGE_RATE_API_URL
      EXCHANGE_RATE_API_CACHE_MAX_RESULTS: $EXCHANGE_RATE_API_CACHE_MAX_RESULTS
      DB_HOST: postgres
      DB_PORT: $DB_PORT
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      ZIPKIN_URL: http://zipkin:9411/api/v2/spans
      TZ: UTC
      NODE_OPTIONS: --enable-source-maps
    depends_on:
      - postgres
      - zipkin

  postgres:
    image: postgres:14.2-alpine3.15
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      PGPORT: ${DB_PORT}
      
  zipkin:
    image: openzipkin/zipkin:2.23 
    hostname: zipkin
    ports:
      - "9411:9411"
